export default [
  { idMeal: '12345',
    strMeal: 'Corba',
    strDrinkAlternate: null,
    strCategory: 'Side',
    strArea: 'Turkish',
    strInstructions: 'test instructions',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/58oia61564916529.jpg',
    strTags: 'Soup',
    strIngredient1: 'Lentils',
    strIngredient2: 'Onion',
    strIngredient3: 'Carrots',
    strIngredient4: 'Tomato Puree',
    strIngredient5: 'Cumin',
    strIngredient6: 'Paprika',
    strIngredient7: 'Mint',
    strIngredient8: 'Thyme',
    strIngredient9: 'Black Pepper',
    strIngredient10: 'Red Pepper Flakes',
    strIngredient11: 'Vegetable Stock',
    strIngredient12: 'Water',
    strIngredient13: 'Sea Salt',
  },
  {
    idDrink: '54321',
    strDrink: 'Drink Test',
    strCategory: 'Ordinary Drink',
    strAlcoholic: 'Optional alcohol',
    strGlass: 'Collins Glass',
    strInstructions: 'drink instructions',
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/vyxwut1468875960.jpg',
    strIngredient1: 'Galliano',
    strIngredient2: 'Ginger ale',
    strIngredient3: 'Ice',
  },
];
